BINANCE_FUTURE_API_KEY = "xxxx"
BINANCE_FUTURE_API_SECRET = "xxxx"
BINANCE_FUTURE_TESTING = True

BINANCE_SPOT_API_KEY = "xxxx"
BINANCE_SPOT_API_SECRET = "xxxx"
BINANCE_SPOT_TESTING = True

SETTRADE_APP_KEY = "xxx"
SETTRADE_APP_SECRET = "xxx"
SETTRADE_TESTING = "SANDBOX"
SETTRADE_SPOT_ACC_NO = "pyybott-E"
SETTRADE_FUTURE_ACC_NO = "pyybott-D"
SETTRADE_PINCODE = "000000"